---
mesos_ip: "{{ ipaddr }}"
mesos_hostname: "{{ ipaddr }}"
mesos_apt_package: "mesos=1.2.0-2.0.6"
mesos_containerizers: "docker,mesos"
mesos_install_mode: "slave"
mesos_additional_configs:
  - name: LOG_LEVEL
    value: INFO

mesos_slave_additional_configs:
  - name: LOGGING_LEVEL
    value: INFO
  - name: RESOURCES
    value: '"cpus:1.2;mem:3000;disk:102400;ports:[20000-60000];cpus(system):0.5;mem(system):1536;disk(system):10240;ports(system):[1-10000];"'